CREATE DATABASE DB_PRA

GO
USE DB_PRA
CREATE TABLE Author
(
	IDAuthor INT PRIMARY KEY IDENTITY,
	FullName NVARCHAR(200) NOT NULL,
	Description NVARCHAR(2000),
	PicturePath NVARCHAR(MAX),
	IsDeleted BIT DEFAULT 0
)

CREATE TABLE "Status"
(
	IDStatus INT PRIMARY KEY IDENTITY,
	StatusName NVARCHAR(100) NOT NULL
)

CREATE TABLE Book
(
	IDBook INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(1000) NOT NULL,
	IDAuthor INT FOREIGN KEY REFERENCES Author(IDAuthor) NOT NULL,
	PicturePath NVARCHAR(MAX),
	Price DECIMAL NOT NULL,
	LoanPrice DECIMAL NOT NULL,
	ISBN NVARCHAR(1000) NOT NULL,
	IDStatus INT FOREIGN KEY REFERENCES [Status](IDStatus) NOT NULL,
	Quantity INT NOT NULL,
	"Description" NVARCHAR(MAX),
	Demand INT DEFAULT 0
)

CREATE TABLE [User]
(
	IDUser INT PRIMARY KEY IDENTITY,
	UserCode NVARCHAR(11) NOT NULL, --A2312220001 OR U2312220001
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	DeletedAt DATETIME NULL,
	DateOfBirth DATE,
	Email NVARCHAR(500) UNIQUE NOT NULL,
	EmailConfirmed BIT, 
	PasswordHash NVARCHAR(MAX),
	PasswordConfirmed BIT DEFAULT 0,
	CityName NVARCHAR(100),
	ZipCode INT,
	"Address" NVARCHAR(100),
	IsAdmin BIT DEFAULT 0,
	OIB NVARCHAR(11),
	WorkPosition NVARCHAR(100)

)

CREATE TABLE Purchase
(
	IDPurchase INT PRIMARY KEY IDENTITY,
	IDBook INT FOREIGN KEY REFERENCES Book(IDBook) NOT NULL,
	IDUser INT FOREIGN KEY REFERENCES [User](IDUser) NOT NULL,
	PurchaseDate DATETIME NOT NULL
)

CREATE TABLE Loan
(
	IDLoan INT PRIMARY KEY IDENTITY,
	IDBook INT FOREIGN KEY REFERENCES Book(IDBook) NOT NULL,
	IDUser INT FOREIGN KEY REFERENCES [User](IDUser) NOT NULL,
	LoanBeginDate DATETIME NOT NULL,
	LoanEndDate DATETIME NOT NULL,
	TotalDelayAmount DECIMAL DEFAULT 0,
	DelayPrice DECIMAL NOT NULL,
	IsSettled BIT DEFAULT 0
)







